export const projectsData = [
  {
    id: 17,
    title: "AchievementTravels",
    description: "Travel Agency Website",
    image: "/images/projects/achievementtravels.png",
    tech: [
      "React.JS",
      "MongoDB",
      "Javascript",
      "TailwindCSS",
      "CSS",
      "Express.JS",
      "Node.JS",
    ],
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://achievementtravels.vercel.app/",
  },
  {
    id: 16,
    title: "VoyageVerse",
    description: "Your Ultimate Travel Companion",
    image: "/images/projects/voyageverse.png",
    tech: [
      "Next.JS",
      "React.JS",
      "MongoDB",
      "Cloudinary",
      "Javascript",
      "TailwindCSS",
      "CSS",
    ],
    tag: ["All", "Web"],
    gitUrl: "https://github.com/arhaanhamid/voyageverse-nextjs/",
    previewUrl: "https://voyageverse-nextjs.vercel.app/",
  },
  {
    id: 15,
    title: "AI IdeaBot",
    description: "Empowering Your Ideas with AI",
    image: "/images/projects/ai-ideabot.png",
    tech: ["React.JS", "ExpressJS", "Javascript", "CSS"],
    tag: ["All", "Web"],
    gitUrl: "https://https://github.com/arhaanhamid/ai-ideabot-mern/",
    previewUrl: "/",
  },
  {
    id: 14,
    title: "Tasker",
    description: "Task Management Webapp",
    image: "/images/projects/tasker.png",
    tech: [
      "Next.JS",
      "React.JS",
      "MongoDB",
      "Javascript",
      "TailwindCSS",
      "CSS",
    ],
    tag: ["All", "Web"],
    gitUrl: "https://github.com/arhaanhamid/tasker-nextjs/",
    previewUrl: "https://tasker-nextjs.vercel.app/",
  },
  {
    id: 13,
    title: "Bloggy",
    description: "Open Blog App",
    image: "/images/projects/blog.png",
    tech: ["Next.JS", "React.JS", "MongoDB", "Javascript", "CSS"],
    tag: ["All", "Web"],
    gitUrl: "https://github.com/arhaanhamid/bloggy-nextjs/",
    previewUrl: "https://bloggy-nextjs.vercel.app/",
  },
  {
    id: 12,
    title: "Portfolio",
    description: "Personal Portfolio",
    image: "/images/projects/portfolio.png",
    tag: ["All", "Web"],
    tech: ["Next.JS", "React.JS", "Javascript", "TailwindCSS", "Framer-Motion"],
    gitUrl: "https://github.com/arhaanhamid/portfolio-nextjs",
    previewUrl: "https://arhaanhamid.vercel.app/",
  },
  {
    id: 11,
    title: "Share Prompts",
    description: "Find and Share exceptional prompts",
    image: "/images/projects/share_prompts.png",
    tag: ["All", "Web"],
    tech: ["Next.JS", "React.JS", "MongoDB", "Javascript", "TailwindCSS"],
    gitUrl: "https://github.com/arhaanhamid/share-prompts",
    previewUrl: "https://shareprompts-next.vercel.app/",
  },
  {
    id: 10,
    title: "Solo Leveling",
    description: "Top-Down Prespective Action Game",
    image: "/images/projects/solo_leveling.jpg",
    tag: ["All", "Application"],
    tech: ["Core Java", "JavaFX"],
    gitUrl: "https://github.com/arhaanhamid/sololeveling_javafx_game",
    previewUrl: "/",
  },
  {
    id: 9,
    title: "Quiz Me",
    description: "An quiz/trivia webapp to test your knowledge",
    image: "/images/projects/quiz_me.jpg",
    tag: ["All", "Web"],
    tech: ["React.JS", "HTML", "CSS", "Javascript"],
    gitUrl: "https://github.com/arhaanhamid/quiz-me_react",
    previewUrl: "https://quiz-me-react.vercel.app/",
  },
  {
    id: 8,
    title: "Tenzies",
    description: "Tenzies based game made using react",
    image: "/images/projects/tenzies_game.png",
    tag: ["All", "Web"],
    tech: ["React.JS", "HTML", "CSS", "Javascript"],
    gitUrl: "https://github.com/arhaanhamid/tenzies-game_react",
    previewUrl: "https://tenzies-game-react-ochre.vercel.app/",
  },
  {
    id: 7,
    title: "BlackBoxes",
    description: "A simple webapp puzzle game made using react",
    image: "/images/projects/black_boxes.png",
    tag: ["All", "Web"],
    tech: ["React.JS", "HTML", "CSS", "Javascript"],
    gitUrl: "https://github.com/arhaanhamid/blackboxes-game_react",
    previewUrl: "https://blackboxes-game-react.vercel.app/",
  },
  {
    id: 6,
    title: "Meme Generator",
    description:
      "Generate your own memes using this meme generator made using react",
    image: "/images/projects/meme_generator.png",
    tag: ["All", "Web"],
    tech: ["React.JS", "HTML", "CSS", "Javascript"],
    gitUrl: "https://github.com/arhaanhamid/Meme-Generator_react",
    previewUrl: "https://meme-generator-react-psi.vercel.app/",
  },
  {
    id: 5,
    title: "URL Shortener",
    description:
      "Shorten your long urls for free and keep them easy to remember.",
    image: "/images/projects/api.png",
    tag: ["All", "Web", "Microservices"],
    tech: ["HTML", "CSS", "Javascript"],
    gitUrl: "https://github.com/arhaanhamid/url-shortener-microservice",
    previewUrl: "https://url-shortener-k8ej.onrender.com/",
  },
  {
    id: 4,
    title: "Exercise Tracker",
    description: "Track you daily exercise and keep a log of them.",
    image: "/images/projects/api.png",
    tag: ["All", "Web", "Microservices"],
    tech: ["HTML", "CSS", "Javascript"],
    gitUrl: "https://github.com/arhaanhamid/exercise-tracker-microservice",
    previewUrl: "https://exercise-tracker-microservice-if04.onrender.com/",
  },
  {
    id: 3,
    title: "File Metadata",
    description: "Upload a file and get its metadata.",
    image: "/images/projects/api.png",
    tag: ["All", "Web", "Microservices"],
    tech: ["HTML", "CSS", "Javascript"],
    gitUrl: "https://github.com/arhaanhamid/file-metadata-microservice",
    previewUrl: "https://file-metadata-microservice-p536.onrender.com/",
  },
  {
    id: 2,
    title: "Request Header Parser",
    description: "Get the header data of any request.",
    image: "/images/projects/api.png",
    tag: ["All", "Web", "Microservices"],
    tech: ["HTML", "CSS", "Javascript"],
    gitUrl: "https://github.com/arhaanhamid/request-header-parser-microservice",
    previewUrl: "https://request-header-parser-microservice-cjqj.onrender.com/",
  },
  {
    id: 1,
    title: "TImestamp Microservice",
    description: "Write any date in the url and get its proper timestamp.",
    image: "/images/projects/api.png",
    tag: ["All", "Web", "Microservices"],
    tech: ["HTML", "CSS", "Javascript"],
    gitUrl: "https://github.com/arhaanhamid/timestamp-microservice",
    previewUrl: "https://timestamp-microservice-85un.onrender.com/",
  },
];
